jenkins-job-configuration-default:
  output-dir: "/data/jenkins/jobs"
  jobs:
    - job-bundle-name: "test jobs"
      common-template-params:
        daystokeep: "100"
        numtokeep: "100"
      jenkins-jobs:
        - name: "test-jenkins-yml-job"
          description: "Skal kunne lave en pipeline ud fra denne yml og parametrene herunder"
          template: "yml-test.jenkinsfile"
          template-params:
            context: "test"
